package hanghae.four.taxiservice.infrastructures.taxi.call.exception

class CallNotFoundException : RuntimeException("Call Not Found")
