package hanghae.four.taxiservice.infrastructure.taxi.call.exception

class CallNotFoundException : RuntimeException("Call Not Found")
